name: VV_Forecasting

channels:
  # Conda forge - gives us lots of community-built Python packages, see https://conda-forge.org/ for details
  - conda-forge  

dependencies:
  - numpy
  - pandas
  - xlrd
  - feather-format
  - ipykernel
  - jupyter
  - xlsxwriter
  - seaborn
  - scikit-learn
  - keras
  - pip:
    - sos-essentials

